### ISSUE TITLE
Evolve a json/yaml for describing test scenarios

### ISSUE THREAD

**Issue by ashetty1** [redhat-developer/ocdev#113]
Tests for `ocdev` should be described in json/yaml which would make it easy for maintainability and scalability purposes.

A test scenario description could look something like this:

```
commands:
  - ocdev application create
  - ocdev component create nodejs --git=<url>
  
assert:
  - url:  <route_url>
  - stringContains: "successfully created"
```
