### ISSUE TITLE
implement `application create`

### ISSUE THREAD

**Issue by kadel** [redhat-developer/ocdev#12]
Because there is nothing that can represent the application in openshift we need to create something. 

First we should figure out where we will keep application metadata and also context of active application.

It can be either client side (in config files in directory like `~/.ocdev/<application_name>`).

Or it could be in cluster using [CRD](https://docs.openshift.org/latest/admin_guide/custom_resource_definitions.html). We could take inspiration form [Kubernetes Application API](https://github.com/kow3ns/community/blob/4417f5e7c11dd6deb8b54d87c49d78fc8c66a7ae/keps/sig-apps/0003-kubernetes-application-api.md) proposal, and use something like this:

```
apiVersion: ocdev.apps.openshift.com/v1beta1
Kind: Application
metadata:
  name: wordpress
spec:
  components:
    - wordpress-mysql-hsvc:
        version: v1
        kind: Service
    - wordpress-mysql:
        group: apps
        version: v1
        kind: StatefulSet
    - wordpress-webserver-hsvc:
        version: v1
        kind: Service
    - wordpress-webserver-svc:
        version: v1
        kind: Service
    - wordpress-mysql:
        group: apps
        version: v1
        kind: StatefulSet
    - wordpress-webserver:
        group: apps
        version: v1
        kind: StatefulSet

```
