### ISSUE TITLE
Build a functional e2e tests framework for the project

### ISSUE THREAD

**Issue by containscafeine** [redhat-developer/ocdev#4]
ping @ashetty1 @kadel 

We could use something like -
```yaml
commands:
  - ocdev application create
  - ocdev component create nodejs --git=<url>
  
assert:
- url:  <route_url>
  output: "successfully created"
  exitCode: 0
```
